# Generated by Django 3.2.3 on 2021-09-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
